// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vanmumzuactiefvksrvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbm11bXp1YWN0aWVmdmtzcnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzI0NzQsImV4cCI6MjA3MzYwODQ3NH0.vvR0z6Jt8sDaMK1zisl9xmDsUUp6aIkVsHstQ9qm1n8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});